# Generated by Django 3.2.8 on 2021-10-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duvida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField(verbose_name='Pergunta')),
                ('resposta', models.TextField(verbose_name='Resposta')),
            ],
            options={
                'verbose_name': 'Dúvida frequente',
                'verbose_name_plural': 'Dúvidas frequentes',
            },
        ),
    ]
