# Generated by Django 3.1.5 on 2021-10-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_duvida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comorbidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Comorbidade',
                'verbose_name_plural': 'Comorbidades',
            },
        ),
    ]
