# Generated by Django 3.2.9 on 2021-11-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_consulta_exame_hospital_medico'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='hora',
            field=models.TimeField(null=True, verbose_name='Hora'),
        ),
    ]
