# Generated by Django 3.2.9 on 2021-11-04 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_consulta_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='todo.medico', verbose_name='Médico'),
        ),
    ]
