# Generated by Django 3.2.9 on 2021-11-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_consulta_medico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='endreco',
            new_name='endereco',
        ),
        migrations.AlterField(
            model_name='consulta',
            name='requerimentoExame',
            field=models.FileField(max_length=255, null=True, upload_to='static/requerimentos'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='arquivo',
            field=models.FileField(max_length=255, null=True, upload_to='static/exames'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='descricao',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
    ]
