# Generated by Django 3.1.5 on 2021-11-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20211104_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='email',
            field=models.CharField(max_length=20, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='sangue',
            field=models.CharField(max_length=3, null=True, verbose_name='Tipo Sanguíneo'),
        ),
    ]
