# Generated by Django 3.1.5 on 2021-11-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_auto_20211108_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Descrição')),
                ('email', models.CharField(max_length=100, verbose_name='exemplo@mail.com')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
        migrations.AlterField(
            model_name='paciente',
            name='comorbidades',
            field=models.ManyToManyField(blank=True, to='todo.Comorbidade', verbose_name='Comorbidades'),
        ),
    ]
